trigger:
  branches:
    include:
      - main  # Trigger pipeline for changes in the main branch

pool:
  name: Default  # Use the default agent pool with your self-hosted agent

variables:
  buildConfiguration: 'Release'

stages:
# Build Stage
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    displayName: "Compile and Build the Project"
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
        checkLatest: true
      displayName: "Install Node.js"

    - script: |
        echo "Installing dependencies..."
        npm install
      displayName: "Install Dependencies"

    - script: |
        echo "Building the project..."
        npm run build
      displayName: "Build the Project"

# Test Stage
- stage: Test
  displayName: "Test Stage"
  dependsOn: Build
  jobs:
  - job: TestJob
    displayName: "Run Unit Tests and Generate Coverage Report"
    steps:
    - script: |
        echo "Running unit tests..."
        npm test -- --coverage
      displayName: "Run Tests and Generate Code Coverage"

