# Node.js with React and Express Build Pipeline

trigger:
  branches:
    include:
      - main

pool:
  name: Default 

stages:
# Build Stage
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: Build_Job
    displayName: "Build Frontend and Backend"
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    # Build Frontend
    - script: |
        cd $(System.DefaultWorkingDirectory)/frontend
        npm install
        npm run build
      displayName: 'Install and Build Frontend'

    # Build Backend
    - script: |
        cd $(System.DefaultWorkingDirectory)/backend
        npm install --legacy-peer-deps
      displayName: 'Install Backend Dependencies (With Peer Conflict Fix)'

 

    # Publish Build Artifact
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'BuildArtifact'
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Publish Build Artifact'

# Test Stage
- stage: Test
  displayName: "Test Stage"
  dependsOn: Build
  jobs:
  - job: Test_Job
    displayName: "Run Frontend and Backend Tests"
    steps:
    # Frontend Tests
    - script: |
        cd $(System.DefaultWorkingDirectory)/frontend
        npm install
        npm test
      displayName: 'Run Frontend Tests'

    # Backend Tests
    - script: |
        cd $(System.DefaultWorkingDirectory)/backend
        npm install --legacy-peer-deps
        npm test
      displayName: 'Run Backend Tests'
