# Node.js with React and Express Build Pipeline

trigger:
  branches:
    include:
      - main

pool:
  name: Default 

stages:
# Build Stage
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: Build_Job
    displayName: "Build Frontend and Backend"
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    # Build Frontend
    - script: |
        cd $(System.DefaultWorkingDirectory)/frontend
        npm install
        npm run build
      displayName: 'Install and Build Frontend'

    # Build Backend
    - script: |
        cd $(System.DefaultWorkingDirectory)/backend
        npm install
      displayName: 'Install Backend Dependencies'

    # Archive Code
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
        exclude: |
          node_modules/**
          frontend/node_modules/**
          frontend/build/**
        verbose: true
      displayName: 'Archive Code'

    # Publish Build Artifact
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'BuildArtifact'
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Publish Build Artifact'

# Test Stage
- stage: Test
  displayName: "Test Stage"
  dependsOn: Build
  jobs:
  - job: Test_Job
    displayName: "Run Frontend and Backend Tests"
    steps:
    # Frontend Tests
    - script: |
        cd $(System.DefaultWorkingDirectory)/frontend
        npm install
        npm test
      displayName: 'Run Frontend Tests'

    # Backend Tests
    - script: |
        cd $(System.DefaultWorkingDirectory)/backend
        npm install
        npm test
      displayName: 'Run Backend Tests'
