trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Use your self-hosted agent pool

stages:
# Build Stage
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: Build_Job
    displayName: "Build Frontend and Backend"
    steps:
    # Install Node.js
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    # Build Frontend
    - script: |
        cd $(System.DefaultWorkingDirectory)/frontend
        npm install
        npm run build
      displayName: 'Install and Build Frontend'

    # Build Backend
    - script: |
        cd $(System.DefaultWorkingDirectory)/backend
        npm install --legacy-peer-deps
        npm run build
      displayName: 'Install and Build Backend'

# Test Stage
- stage: Test
  displayName: "Test Stage"
  dependsOn: Build
  jobs:
  - job: Test_Job
    displayName: "Run Frontend and Backend Tests"
    steps:
    # Frontend Tests
    - script: |
        cd $(System.DefaultWorkingDirectory)/frontend
        npm install
        npm test -- --coverage
      displayName: 'Run Frontend Tests and Generate Coverage'

    # Backend Tests
    - script: |
        cd $(System.DefaultWorkingDirectory)/backend
        npm install --legacy-peer-deps
        npm test -- --coverage
      displayName: 'Run Backend Tests and Generate Coverage'
